### ISSUE TITLE
Error when running runTest

### ISSUE THREAD

**Issue by melaasar** [IncQueryLabs/MD_plugin_skeleton#31]
Hello, I built the project with ./gradlew build assemble. Then, when I execute the tests with:
./gradlew runTest
I get the following exception:
2020-03-23 14:25:41,359 [main] ERROR GENERAL - Commandline action com.incquerylabs.magicdraw.plugin.example.test.runner.TestRunner not found.
java.lang.IllegalArgumentException: Commandline action com.incquerylabs.magicdraw.plugin.example.test.runner.TestRunner not found.
        at com.nomagic.magicdraw.commandline.CommandLineActionLauncher.newActionExecuter(CommandLineActionLauncher.java:71)
        at com.nomagic.magicdraw.commandline.CommandLineActionLauncher.launch(CommandLineActionLauncher.java:36)
        at com.nomagic.magicdraw.ApplicationGateway.start(ApplicationGateway.java:46)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
 
Do you know why?

**Comment by ujhelyiz** [comment]
Hi,

the problem here is almost certainly caused by either the plug-in or the test plug-in not starting correctly that should be described somewhere earlier in the Magicdraw logs, but without that information I cannot really tell what might be the problem. Could you please look for that in the logs?

Thanks.
